[package]
name = "drivechain-cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
cxx = "1.0"
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "5301b0d38273bf8a0a1aa2c42106f0283323a3e0" }
thiserror = "1.0.31"
hex = "0.4.3"

[build-dependencies]
cxx-build = "1.0"
