[package]
name = "drivechain-cpp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
cxx = "1.0"
drivechain = { git = "https://github.com/nchashch/drivechain", rev = "07b159469a03362b1aafd7b363323e712385c1b5" }
thiserror = "1.0.31"
hex = "0.4.3"

[build-dependencies]
cxx-build = "1.0"
